### Bibliotecas

In [1]:
import pandas as pd

### Estudo de caso

In [2]:
internacoes = pd.read_csv("data/internacoes.csv")
ambulatorio = pd.read_csv("data/ambulatorio.csv")

In [3]:
internacoes

,FID,co_ibge,no_municipio,nu_ocorrencias,mp_municipio
0,vw_geo__intern_hosp__doencas_cardiov__municipi...,292560,Presidente Dutra,3,MULTIPOLYGON (((-42.054286999999995 -11.233391...
1,vw_geo__intern_hosp__doencas_cardiov__municipi...,411520,Maringá,16,MULTIPOLYGON (((-51.868474 -23.288010999999997...
2,vw_geo__intern_hosp__doencas_cardiov__municipi...,421820,Timbó,2,"MULTIPOLYGON (((-49.305028 -26.847965, -49.311..."
3,vw_geo__intern_hosp__doencas_cardiov__municipi...,411990,Ponta Grossa,12,"MULTIPOLYGON (((-50.275841 -25.28917, -50.2697..."
4,vw_geo__intern_hosp__doencas_cardiov__municipi...,355540,Ubatuba,2,MULTIPOLYGON (((-45.276685 -23.578336999999998...
...,...,...,...,...,...
5567,vw_geo__intern_hosp__doencas_cardiov__municipi...,317065,Vargem Grande do Rio Pardo,0,"MULTIPOLYGON (((-42.229817 -15.418061, -42.237..."
5568,vw_geo__intern_hosp__doencas_cardiov__municipi...,280220,Feira Nova,0,"MULTIPOLYGON (((-37.395768 -10.288438, -37.389..."
5569,vw_geo__intern_hosp__doencas_cardiov__municipi...,412625,Sarandi,0,MULTIPOLYGON (((-51.843016999999996 -23.393663...
5570,vw_geo__intern_hosp__doencas_cardiov__municipi...,315680,Sabinópolis,0,"MULTIPOLYGON (((-42.895643 -18.560927, -42.910..."
5571,vw_geo__intern_hosp__doencas_cardiov__municipi...,316805,Taparuba,0,"MULTIPOLYGON (((-41.590903 -19.807335, -41.605..."

In [4]:
ambulatorio

,FID,co_ibge,no_municipio,nu_ocorrencias,mp_municipio
0,vw_geo__atend_ambul__doencas_cardiov__municipi...,110012,Ji-Paraná,2,MULTIPOLYGON (((-61.972666999999994 -10.067528...
1,vw_geo__atend_ambul__doencas_cardiov__municipi...,110028,Rolim de Moura,1,"MULTIPOLYGON (((-61.614219 -11.583829, -61.566..."
2,vw_geo__atend_ambul__doencas_cardiov__municipi...,110030,Vilhena,4,MULTIPOLYGON (((-60.333169999999996 -13.257978...
3,vw_geo__atend_ambul__doencas_cardiov__municipi...,110149,São Francisco do Guaporé,23,MULTIPOLYGON (((-63.684757999999995 -12.453057...
4,vw_geo__atend_ambul__doencas_cardiov__municipi...,130120,Coari,13,"MULTIPOLYGON (((-62.361822999999994 -4.090392,..."
...,...,...,...,...,...
5567,vw_geo__atend_ambul__doencas_cardiov__municipi...,317065,Vargem Grande do Rio Pardo,0,"MULTIPOLYGON (((-42.229817 -15.418061, -42.237..."
5568,vw_geo__atend_ambul__doencas_cardiov__municipi...,280220,Feira Nova,0,"MULTIPOLYGON (((-37.395768 -10.288438, -37.389..."
5569,vw_geo__atend_ambul__doencas_cardiov__municipi...,412625,Sarandi,0,MULTIPOLYGON (((-51.843016999999996 -23.393663...
5570,vw_geo__atend_ambul__doencas_cardiov__municipi...,315680,Sabinópolis,0,"MULTIPOLYGON (((-42.895643 -18.560927, -42.910..."
5571,vw_geo__atend_ambul__doencas_cardiov__municipi...,316805,Taparuba,0,"MULTIPOLYGON (((-41.590903 -19.807335, -41.605..."

In [5]:
internacoes = (
    internacoes
    .sort_values(by="nu_ocorrencias", ascending=False)
    .reset_index(drop=True)
)

internacoes

,FID,co_ibge,no_municipio,nu_ocorrencias,mp_municipio
0,vw_geo__intern_hosp__doencas_cardiov__municipi...,312090,Curvelo,288,"MULTIPOLYGON (((-44.157509 -18.766831, -44.157..."
1,vw_geo__intern_hosp__doencas_cardiov__municipi...,313350,Itapecerica,143,"MULTIPOLYGON (((-45.011896 -20.570346, -45.018..."
2,vw_geo__intern_hosp__doencas_cardiov__municipi...,410420,Campo Largo,121,"MULTIPOLYGON (((-49.374463 -25.513424, -49.388..."
3,vw_geo__intern_hosp__doencas_cardiov__municipi...,292740,Salvador,115,"MULTIPOLYGON (((-38.585586 -13.012673, -38.580..."
4,vw_geo__intern_hosp__doencas_cardiov__municipi...,211130,São Luís,107,"MULTIPOLYGON (((-44.22085 -2.473928, -44.20549..."
...,...,...,...,...,...
5567,vw_geo__intern_hosp__doencas_cardiov__municipi...,317065,Vargem Grande do Rio Pardo,0,"MULTIPOLYGON (((-42.229817 -15.418061, -42.237..."
5568,vw_geo__intern_hosp__doencas_cardiov__municipi...,280220,Feira Nova,0,"MULTIPOLYGON (((-37.395768 -10.288438, -37.389..."
5569,vw_geo__intern_hosp__doencas_cardiov__municipi...,412625,Sarandi,0,MULTIPOLYGON (((-51.843016999999996 -23.393663...
5570,vw_geo__intern_hosp__doencas_cardiov__municipi...,315680,Sabinópolis,0,"MULTIPOLYGON (((-42.895643 -18.560927, -42.910..."
5571,vw_geo__intern_hosp__doencas_cardiov__municipi...,293290,Valença,0,MULTIPOLYGON (((-38.950753999999996 -13.389911...

In [6]:
ambulatorio = (
    ambulatorio
    .sort_values(by="nu_ocorrencias", ascending=False)
    .reset_index(drop=True)
)

ambulatorio

,FID,co_ibge,no_municipio,nu_ocorrencias,mp_municipio
0,vw_geo__atend_ambul__doencas_cardiov__municipi...,314800,Patos de Minas,2280,"MULTIPOLYGON (((-46.402797 -18.880553, -46.417..."
1,vw_geo__atend_ambul__doencas_cardiov__municipi...,316720,Sete Lagoas,2218,"MULTIPOLYGON (((-44.315023 -19.591955, -44.306..."
2,vw_geo__atend_ambul__doencas_cardiov__municipi...,330455,Rio de Janeiro,1820,"MULTIPOLYGON (((-43.272831 -22.809829, -43.266..."
3,vw_geo__atend_ambul__doencas_cardiov__municipi...,431680,Santa Cruz do Sul,682,MULTIPOLYGON (((-52.435265 -29.378214999999997...
4,vw_geo__atend_ambul__doencas_cardiov__municipi...,430130,Arroio Grande,567,MULTIPOLYGON (((-53.305637999999995 -32.217642...
...,...,...,...,...,...
5567,vw_geo__atend_ambul__doencas_cardiov__municipi...,317065,Vargem Grande do Rio Pardo,0,"MULTIPOLYGON (((-42.229817 -15.418061, -42.237..."
5568,vw_geo__atend_ambul__doencas_cardiov__municipi...,280220,Feira Nova,0,"MULTIPOLYGON (((-37.395768 -10.288438, -37.389..."
5569,vw_geo__atend_ambul__doencas_cardiov__municipi...,412625,Sarandi,0,MULTIPOLYGON (((-51.843016999999996 -23.393663...
5570,vw_geo__atend_ambul__doencas_cardiov__municipi...,315680,Sabinópolis,0,"MULTIPOLYGON (((-42.895643 -18.560927, -42.910..."
5571,vw_geo__atend_ambul__doencas_cardiov__municipi...,420470,Cunha Porã,0,"MULTIPOLYGON (((-53.111833 -26.924466, -53.119..."

In [7]:
datasets = {
    nome: obj
    for nome, obj in globals().items()
    if isinstance(obj, pd.DataFrame)
    and "no_municipio" in obj.columns
    and not nome.startswith("_")
}

for nome, df in datasets.items():
    chaves_unicas = sorted(df["no_municipio"].dropna().astype(str).unique())
    print(f"\n{nome} -> {len(chaves_unicas)} chaves únicas de no_municipio")
    print(chaves_unicas)

internacoes -> 5300 chaves únicas de no_municipio

In [8]:
chaves_internacoes = set(internacoes["no_municipio"].dropna().astype(str).unique())
chaves_ambulatorio = set(ambulatorio["no_municipio"].dropna().astype(str).unique())

chaves_comuns = sorted(chaves_internacoes & chaves_ambulatorio)

print(f"Total de chaves comuns: {len(chaves_comuns)}")
chaves_comuns

Total de chaves comuns: 5300

['Abadia de Goiás',
 'Abadia dos Dourados',
 'Abadiânia',
 'Abaetetuba',
 'Abaeté',
 'Abaiara',
 'Abaré',
 'Abatiá',
 'Abaíra',
 'Abdon Batista',
 'Abel Figueiredo',
 'Abelardo Luz',
 'Abre Campo',
 'Abreu e Lima',
 'Abreulândia',
 'Acaiaca',
 'Acajutiba',
 'Acarape',
 'Acaraú',
 'Acari',
 'Acará',
 'Acauã',
 'Aceguá',
 'Acopiara',
 'Acorizal',
 'Acrelândia',
 'Acreúna',
 'Adamantina',
 'Adelândia',
 'Adolfo',
 'Adrianópolis',
 'Adustina',
 'Afogados da Ingazeira',
 'Afonso Bezerra',
 'Afonso Cláudio',
 'Afonso Cunha',
 'Afrânio',
 'Afuá',
 'Agrestina',
 'Agricolândia',
 'Agrolândia',
 'Agronômica',
 'Aguanil',
 'Aguaí',
 'Agudo',
 'Agudos',
 'Agudos do Sul',
 'Aguiar',
 'Aguiarnópolis',
 'Aimorés',
 'Aiquara',
 'Aiuaba',
 'Aiuruoca',
 'Ajuricaba',
 'Alagoa',
 'Alagoa Grande',
 'Alagoa Nova',
 'Alagoinha',
 'Alagoinha do Piauí',
 'Alagoinhas',
 'Alambari',
 'Albertina',
 'Alcantil',
 'Alcinópolis',
 'Alcobaça',
 'Alcântara',
 'Alcântaras',
 'Aldeias Altas',
 'Alecrim',
 'Alegre',
 'Alegrete',
 'Alegrete do Piauí',
 'Alegria',
 'Alenquer',
 'Alexandria',
 'Alexânia',
 'Alfenas',
 'Alfredo Chaves',
 'Alfredo Marcondes',
 'Alfredo Vasconcelos',
 'Alfredo Wagner',
 'Algodão de Jandaíra',
 'Alhandra',
 'Aliança',
 'Aliança do Tocantins',
 'Almadina',
 'Almas',
 'Almeirim',
 'Almenara',
 'Almino Afonso',
 'Almirante Tamandaré',
 'Almirante Tamandaré do Sul',
 'Aloândia',
 'Alpercata',
 'Alpestre',
 'Alpinópolis',
 'Alta Floresta',
 "Alta Floresta D'Oeste",
 'Altair',
 'Altamira',
 'Altamira do Maranhão',
 'Altamira do Paraná',
 'Altaneira',
 'Alterosa',
 'Altinho',
 'Altinópolis',
 'Alto Alegre',
 'Alto Alegre do Maranhão',
 'Alto Alegre do Pindaré',
 'Alto Alegre dos Parecis',
 'Alto Araguaia',
 'Alto Bela Vista',
 'Alto Boa Vista',
 'Alto Caparaó',
 'Alto Feliz',
 'Alto Garças',
 'Alto Horizonte',
 'Alto Jequitibá',
 'Alto Longá',
 'Alto Paraguai',
 'Alto Paraná',
 'Alto Paraíso',
 'Alto Paraíso de Goiás',
 'Alto Parnaíba',
 'Alto Piquiri',
 'Alto Rio Doce',
 'Alto Rio Novo',
 'Alto Santo',
 'Alto Taquari',
 'Alto do Rodrigues',
 'Altos',
 'Altônia',
 'Alumínio',
 'Alvarenga',
 'Alvarães',
 'Alvinlândia',
 'Alvinópolis',
 'Alvorada',
 "Alvorada D'Oeste",
 'Alvorada de Minas',
 'Alvorada do Gurguéia',
 'Alvorada do Norte',
 'Alvorada do Sul',
 'Além Paraíba',
 'Amajari',
 'Amambai',
 'Amaporã',
 'Amapá',
 'Amapá do Maranhão',
 'Amaraji',
 'Amaral Ferrador',
 'Amaralina',
 'Amarante',
 'Amarante do Maranhão',
 'Amargosa',
 'Amaturá',
 'Americana',
 'Americano do Brasil',
 'Ametista do Sul',
 'Amontada',
 'Amorinópolis',
 'Amparo',
 'Amparo de São Francisco',
 'Amparo do Serra',
 'Ampére',
 'Amélia Rodrigues',
 'América Dourada',
 'Américo Brasiliense',
 'Américo de Campos',
 'Anadia',
 'Anagé',
 'Anahy',
 'Anajatuba',
 'Anajás',
 'Analândia',
 'Anamã',
 'Ananindeua',
 'Ananás',
 'Anapu',
 'Anapurus',
 'Anastácio',
 'Anaurilândia',
 'Anchieta',
 'Andaraí',
 'Andirá',
 'Andorinha',
 'Andradas',
 'Andradina',
 'Andrelândia',
 'André da Rocha',
 'Angatuba',
 'Angelim',
 'Angelina',
 'Angelândia',
 'Angical',
 'Angical do Piauí',
 'Angico',
 'Angicos',
 'Angra dos Reis',
 'Anguera',
 'Angélica',
 'Anhanguera',
 'Anhembi',
 'Anhumas',
 'Anicuns',
 'Anita Garibaldi',
 'Anitápolis',
 'Anori',
 'Anta Gorda',
 'Antas',
 'Antonina',
 'Antonina do Norte',
 'Antônio Almeida',
 'Antônio Cardoso',
 'Antônio Carlos',
 'Antônio Dias',
 'Antônio Gonçalves',
 'Antônio João',
 'Antônio Martins',
 'Antônio Olinto',
 'Antônio Prado',
 'Antônio Prado de Minas',
 'Anápolis',
 'Anísio de Abreu',
 'Aparecida',
 "Aparecida D'Oeste",
 'Aparecida de Goiânia',
 'Aparecida do Rio Doce',
 'Aparecida do Rio Negro',
 'Aparecida do Taboado',
 'Aperibé',
 'Apiacá',
 'Apiacás',
 'Apiaí',
 'Apicum-Açu',
 'Apiúna',
 'Apodi',
 'Aporá',
 'Aporé',
 'Apuarema',
 'Apucarana',
 'Apuiarés',
 'Apuí',
 'Aquidabã',
 'Aquidauana',
 'Aquiraz',
 'Arabutã',
 'Aracaju',
 'Aracati',
 'Aracatu',
 'Araci',
 'Aracitaba',
 'Aracoiaba',
 'Aracruz',
 'Aragarças',
 'Aragoiânia',
 'Aragominas',
 'Araguacema',
 'Araguaiana',
 'Araguainha',
 'Araguanã',
 'Araguapaz',
 'Araguari',
 'Araguatins',
 'Araguaçu',
 'Araguaína',
 'Araioses',
 'Aral Moreira',
 'Aramari',
 'Arambaré',
 'Arame',
 'Aramina',
 'Arandu',
 'Arantina',
 'Arapeí',
 'Arapiraca',
 'Arapoema',
 'Araponga',
 'Arapongas',
 'Araporã',
 'Arapoti',
 'Araputanga',
 'Arapuá',
 'Arapuã',
 'Araquari',
 'Arara',
 'Araranguá',
 'Araraquara',
 'Araras',
 'Ararendá',
 'Arari',
 'Araricá',
 'Araripe',
 'Araripina',
 'Araruama',
 'Araruna',
 'Arataca',
 'Aratiba',
 'Aratuba',
 'Aratuípe',
 'Araucária',
 'Arauá',
 'Araxá',
 'Araçagi',
 'Araçariguama',
 'Araças',
 'Araçatuba',
 'Araçaí',
 'Araçoiaba',
 'Araçoiaba da Serra',
 'Araçu',
 'Araçuaí',
 'Araújos',
 'Arceburgo',
 'Arco-Íris',
 'Arcos',
 'Arcoverde',
 'Areado',
 'Areal',
 'Arealva',
 'Areia',
 'Areia Branca',
 'Areia de Baraúnas',
 'Areial',
 'Areias',
 'Areiópolis',
 'Arenápolis',
 'Arenópolis',
 'Argirita',
 'Aricanduva',
 'Arinos',
 'Aripuanã',
 'Ariquemes',
 'Ariranha',
 'Ariranha do Ivaí',
 'Armazém',
 'Armação dos Búzios',
 'Arneiroz',
 'Aroazes',
 'Aroeiras',
 'Aroeiras do Itaim',
 'Arraial',
 'Arraial do Cabo',
 'Arraias',
 'Arroio Grande',
 'Arroio Trinta',
 'Arroio do Meio',
 'Arroio do Padre',
 'Arroio do Sal',
 'Arroio do Tigre',
 'Arroio dos Ratos',
 'Artur Nogueira',
 'Aruanã',
 'Arujá',
 'Arvoredo',
 'Arvorezinha',
 'Arês',
 'Ascurra',
 'Aspásia',
 'Assaré',
 'Assaí',
 'Assis',
 'Assis Brasil',
 'Assis Chateaubriand',
 'Assunção',
 'Assunção do Piauí',
 'Astolfo Dutra',
 'Astorga',
 'Atalaia',
 'Atalaia do Norte',
 'Atalanta',
 'Ataléia',
 'Atibaia',
 'Atilio Vivacqua',
 'Augustinópolis',
 'Augusto Corrêa',
 'Augusto Pestana',
 'Augusto Severo',
 'Augusto de Lima',
 'Aurelino Leal',
 'Auriflama',
 'Aurilândia',
 'Aurora',
 'Aurora do Pará',
 'Aurora do Tocantins',
 'Autazes',
 'Avanhandava',
 'Avaré',
 'Avaí',
 'Aveiro',
 'Avelino Lopes',
 'Avelinópolis',
 'Axixá',
 'Axixá do Tocantins',
 'Açailândia',
 'Açu',
 'Açucena',
 'Babaçulândia',
 'Bacabal',
 'Bacabeira',
 'Bacuri',
 'Bacurituba',
 'Bady Bassitt',
 'Baependi',
 'Bagre',
 'Bagé',
 'Baianópolis',
 'Baixa Grande',
 'Baixa Grande do Ribeiro',
 'Baixio',
 'Baixo Guandu',
 'Baião',
 'Balbinos',
 'Baldim',
 'Baliza',
 'Balneário Arroio do Silva',
 'Balneário Barra do Sul',
 'Balneário Camboriú',
 'Balneário Gaivota',
 'Balneário Pinhal',
 'Balneário Piçarras',
 'Balneário Rincão',
 'Balsa Nova',
 'Balsas',
 'Bambuí',
 'Banabuiú',
 'Bananal',
 'Bananeiras',
 'Bandeira',
 'Bandeira do Sul',
 'Bandeirante',
 'Bandeirantes',
 'Bandeirantes do Tocantins',
 'Bannach',
 'Banzaê',
 'Baraúna',
 'Barbacena',
 'Barbalha',
 'Barbosa',
 'Barbosa Ferraz',
 'Barcarena',
 'Barcelona',
 'Barcelos',
 'Bariri',
 'Barra',
 'Barra Bonita',
 "Barra D'Alcântara",
 'Barra Funda',
 'Barra Longa',
 'Barra Mansa',
 'Barra Velha',
 'Barra da Estiva',
 'Barra de Guabiraba',
 'Barra de Santa Rosa',
 'Barra de Santana',
 'Barra de Santo Antônio',
 'Barra de São Francisco',
 'Barra de São Miguel',
 'Barra do Bugres',
 'Barra do Chapéu',
 'Barra do Choça',
 'Barra do Corda',
 'Barra do Garças',
 'Barra do Guarita',
 'Barra do Jacaré',
 'Barra do Mendes',
 'Barra do Ouro',
 'Barra do Piraí',
 'Barra do Quaraí',
 'Barra do Ribeiro',
 'Barra do Rio Azul',
 'Barra do Rocha',
 'Barra do Turvo',
 'Barra dos Coqueiros',
 'Barracão',
 'Barras',
 'Barreira',
 'Barreiras',
 'Barreiras do Piauí',
 'Barreirinha',
 'Barreirinhas',
 'Barreiros',
 'Barretos',
 'Barrinha',
 'Barro',
 'Barro Alto',
 'Barro Duro',
 'Barro Preto',
 'Barrocas',
 'Barrolândia',
 'Barroquinha',
 'Barros Cassal',
 'Barroso',
 'Barueri',
 'Barão',
 'Barão de Antonina',
 'Barão de Cocais',
 'Barão de Cotegipe',
 'Barão de Grajaú',
 'Barão de Melgaço',
 'Barão de Monte Alto',
 'Barão do Triunfo',
 'Bastos',
 'Bataguassu',
 'Batalha',
 'Batatais',
 'Batayporã',
 'Baturité',
 'Bauru',
 'Bayeux',
 'Baía Formosa',
 'Baía da Traição',
 'Bebedouro',
 'Beberibe',
 'Bela Cruz',
 'Bela Vista',
 'Bela Vista da Caroba',
 'Bela Vista de Goiás',
 'Bela Vista de Minas',
 'Bela Vista do Maranhão',
 'Bela Vista do Paraíso',
 'Bela Vista do Piauí',
 'Bela Vista do Toldo',
 'Belford Roxo',
 'Belmiro Braga',
 'Belmonte',
 'Belo Campo',
 'Belo Horizonte',
 'Belo Jardim',
 'Belo Monte',
 'Belo Oriente',
 'Belo Vale',
 'Belterra',
 'Belágua',
 'Belém',
 'Belém de Maria',
 'Belém do Brejo do Cruz',
 'Belém do Piauí',
 'Belém do São Francisco',
 'Beneditinos',
 'Benedito Leite',
 'Benedito Novo',
 'Benevides',
 'Benjamin Constant',
 'Benjamin Constant do Sul',
 'Bento Fernandes',
 'Bento Gonçalves',
 'Bento de Abreu',
 'Bequimão',
 'Berilo',
 'Berizal',
 'Bernardino Batista',
 'Bernardino de Campos',
 'Bernardo Sayão',
 'Bernardo do Mearim',
 'Bertioga',
 'Bertolínia',
 'Bertópolis',
 'Beruri',
 'Betim',
 'Betânia',
 'Betânia do Piauí',
 'Bezerros',
 'Bias Fortes',
 'Bicas',
 'Biguaçu',
 'Bilac',
 'Biquinhas',
 'Birigui',
 'Biritiba Mirim',
 'Biritinga',
 'Bituruna',
 'Blumenau',
 'Boa Esperança',
 'Boa Esperança do Iguaçu',
 'Boa Esperança do Norte',
 'Boa Esperança do Sul',
 'Boa Hora',
 'Boa Nova',
 'Boa Ventura',
 'Boa Ventura de São Roque',
 'Boa Viagem',
 'Boa Vista',
 'Boa Vista da Aparecida',
 'Boa Vista das Missões',
 'Boa Vista do Buricá',
 'Boa Vista do Cadeado',
 'Boa Vista do Gurupi',
 'Boa Vista do Incra',
 'Boa Vista do Ramos',
 'Boa Vista do Sul',
 'Boa Vista do Tupim',
 'Boca da Mata',
 'Boca do Acre',
 'Bocaina',
 'Bocaina de Minas',
 'Bocaina do Sul',
 'Bocaiúva',
 'Bocaiúva do Sul',
 'Bodocó',
 'Bodoquena',
 'Bodó',
 'Bofete',
 'Boituva',
 'Bom Conselho',
 'Bom Despacho',
 'Bom Jardim',
 'Bom Jardim da Serra',
 'Bom Jardim de Goiás',
 'Bom Jardim de Minas',
 'Bom Jesus',
 'Bom Jesus da Lapa',
 'Bom Jesus da Penha',
 'Bom Jesus da Serra',
 'Bom Jesus das Selvas',
 'Bom Jesus de Goiás',
 'Bom Jesus do Amparo',
 'Bom Jesus do Araguaia',
 'Bom Jesus do Galho',
 'Bom Jesus do Itabapoana',
 'Bom Jesus do Norte',
 'Bom Jesus do Oeste',
 'Bom Jesus do Sul',
 'Bom Jesus do Tocantins',
 'Bom Jesus dos Perdões',
 'Bom Lugar',
 'Bom Princípio',
 'Bom Princípio do Piauí',
 'Bom Progresso',
 'Bom Repouso',
 'Bom Retiro',
 'Bom Retiro do Sul',
 'Bom Sucesso',
 'Bom Sucesso de Itararé',
 'Bom Sucesso do Sul',
 'Bombinhas',
 'Bonfim',
 'Bonfim do Piauí',
 'Bonfinópolis',
 'Bonfinópolis de Minas',
 'Boninal',
 'Bonito',
 'Bonito de Minas',
 'Bonito de Santa Fé',
 'Bonópolis',
 'Boqueirão',
 'Boqueirão do Leão',
 'Boqueirão do Piauí',
 'Boquim',
 'Boquira',
 'Boracéia',
 'Borba',
 'Borborema',
 'Borda da Mata',
 'Borebi',
 'Borrazópolis',
 'Borá',
 'Bossoroca',
 'Botelhos',
 'Botucatu',
 'Botumirim',
 'Botuporã',
 'Botuverá',
 'Bozano',
 'Braga',
 'Braganey',
 'Bragança',
 'Bragança Paulista',
 'Branquinha',
 'Brasil Novo',
 'Brasileira',
 'Brasilândia',
 'Brasilândia de Minas',
 'Brasilândia do Sul',
 'Brasilândia do Tocantins',
 'Brasiléia',
 'Brasnorte',
 'Brasília',
 'Brasília de Minas',
 'Brazabrantes',
 'Brazópolis',
 'Braço do Norte',
 'Braço do Trombudo',
 'Braúna',
 'Braúnas',
 'Brejetuba',
 'Brejinho',
 'Brejinho de Nazaré',
 'Brejo',
 'Brejo Alegre',
 'Brejo Grande',
 'Brejo Grande do Araguaia',
 'Brejo Santo',
 'Brejo da Madre de Deus',
 'Brejo de Areia',
 'Brejo do Cruz',
 'Brejo do Piauí',
 'Brejo dos Santos',
 'Brejolândia',
 'Brejão',
 'Brejões',
 'Breu Branco',
 'Breves',
 'Britânia',
 'Brochier',
 'Brodowski',
 'Brotas',
 'Brotas de Macaúbas',
 'Brumadinho',
 'Brumado',
 'Brunópolis',
 'Brusque',
 'Brás Pires',
 'Bueno Brandão',
 'Buenos Aires',
 'Buenópolis',
 'Buerarema',
 'Bugre',
 'Bujari',
 'Bujaru',
 'Buri',
 'Buritama',
 'Buriti',
 'Buriti Alegre',
 'Buriti Bravo',
 'Buriti de Goiás',
 'Buriti do Tocantins',
 'Buriti dos Lopes',
 'Buriti dos Montes',
 'Buriticupu',
 'Buritinópolis',
 'Buritirama',
 'Buritirana',
 'Buritis',
 'Buritizal',
 'Buritizeiro',
 'Butiá',
 'Buíque',
 'Bálsamo',
 'Caapiranga',
 'Caaporã',
 'Caarapó',
 'Caatiba',
 'Cabaceiras',
 'Cabaceiras do Paraguaçu',
 'Cabeceira Grande',
 'Cabeceiras',
 'Cabeceiras do Piauí',
 'Cabedelo',
 'Cabixi',
 'Cabo Frio',
 'Cabo Verde',
 'Cabo de Santo Agostinho',
 'Cabreúva',
 'Cabrobó',
 'Cabrália Paulista',
 'Cacaulândia',
 'Cacequi',
 'Cachoeira',
 'Cachoeira Alta',
 'Cachoeira Dourada',
 'Cachoeira Grande',
 'Cachoeira Paulista',
 'Cachoeira da Prata',
 'Cachoeira de Goiás',
 'Cachoeira de Minas',
 'Cachoeira de Pajeú',
 'Cachoeira do Arari',
 'Cachoeira do Piriá',
 'Cachoeira do Sul',
 'Cachoeira dos Índios',
 'Cachoeiras de Macacu',
 'Cachoeirinha',
 'Cachoeiro de Itapemirim',
 'Cacimba de Areia',
 'Cacimba de Dentro',
 'Cacimbas',
 'Cacimbinhas',
 'Cacique Doble',
 'Cacoal',
 'Caconde',
 'Caculé',
 'Caetanos',
 'Caetanópolis',
 'Caetité',
 'Caeté',
 'Caetés',
 'Cafarnaum',
 'Cafeara',
 'Cafelândia',
 'Cafezal do Sul',
 'Caiabu',
 'Caiana',
 'Caiapônia',
 'Caibaté',
 'Caibi',
 'Caicó',
 'Caieiras',
 'Cairu',
 'Caiuá',
 'Caiçara',
 'Caiçara do Norte',
 'Caiçara do Rio do Vento',
 'Cajamar',
 'Cajapió',
 'Cajari',
 'Cajati',
 'Cajazeiras',
 'Cajazeiras do Piauí',
 'Cajazeirinhas',
 'Cajobi',
 'Cajueiro',
 'Cajueiro da Praia',
 'Cajuri',
 'Cajuru',
 'Caldas',
 'Caldas Brandão',
 'Caldas Novas',
 'Caldazinha',
 'Caldeirão Grande',
 'Caldeirão Grande do Piauí',
 'Califórnia',
 'Calmon',
 'Calumbi',
 'Calçado',
 'Calçoene',
 'Camacan',
 'Camacho',
 'Camalaú',
 'Camamu',
 'Camanducaia',
 'Camapuã',
 'Camaquã',
 'Camaragibe',
 'Camargo',
 'Camaçari',
 'Cambará',
 'Cambará do Sul',
 'Cambira',
 'Camboriú',
 'Cambuci',
 'Cambuquira',
 'Cambuí',
 'Cambé',
 'Cametá',
 'Camocim',
 'Camocim de São Félix',
 'Campanha',
 'Campanário',
 'Campestre',
 'Campestre da Serra',
 'Campestre de Goiás',
 'Campestre do Maranhão',
 'Campina Grande',
 'Campina Grande do Sul',
 'Campina Verde',
 'Campina da Lagoa',
 'Campina das Missões',
 'Campina do Monte Alegre',
 'Campina do Simão',
 'Campinas',
 'Campinas do Piauí',
 'Campinas do Sul',
 'Campinaçu',
 'Campinorte',
 'Campinápolis',
 'Campo Alegre',
 'Campo Alegre de Goiás',
 'Campo Alegre de Lourdes',
 'Campo Alegre do Fidalgo',
 'Campo Azul',
 'Campo Belo',
 'Campo Belo do Sul',
 'Campo Bom',
 'Campo Bonito',
 'Campo Erê',
 'Campo Florido',
 'Campo Formoso',
 'Campo Grande',
 'Campo Grande do Piauí',
 'Campo Largo',
 'Campo Largo do Piauí',
 'Campo Limpo Paulista',
 'Campo Limpo de Goiás',
 'Campo Magro',
 'Campo Maior',
 'Campo Mourão',
 'Campo Novo',
 'Campo Novo de Rondônia',
 'Campo Novo do Parecis',
 'Campo Redondo',
 'Campo Verde',
 'Campo do Brito',
 'Campo do Meio',
 'Campo do Tenente',
 'Campos Altos',
 'Campos Belos',
 'Campos Borges',
 'Campos Gerais',
 'Campos Lindos',
 'Campos Novos',
 'Campos Novos Paulista',
 'Campos Sales',
 'Campos Verdes',
 'Campos de Júlio',
 'Campos do Jordão',
 'Campos dos Goytacazes',
 'Camutanga',
 'Cana Verde',
 'Canabrava do Norte',
 'Cananéia',
 'Canapi',
 'Canarana',
 'Canas',
 'Canavieira',
 'Canavieiras',
 'Canaã',
 'Canaã dos Carajás',
 'Candeal',
 'Candeias',
 'Candeias do Jamari',
 'Candelária',
 'Candiba',
 'Candiota',
 'Candói',
 'Canela',
 'Canelinha',
 'Canguaretama',
 'Canguçu',
 'Canhoba',
 'Canhotinho',
 'Canindé',
 'Canindé de São Francisco',
 'Canitar',
 'Canoas',
 'Canoinhas',
 'Cansanção',
 'Cantagalo',
 'Cantanhede',
 'Canto do Buriti',
 'Cantá',
 'Canudos',
 'Canudos do Vale',
 'Canutama',
 'Canápolis',
 'Capanema',
 'Caparaó',
 'Capela',
 'Capela Nova',
 'Capela de Santana',
 'Capela do Alto',
 'Capela do Alto Alegre',
 'Capelinha',
 'Capetinga',
 'Capim',
 'Capim Branco',
 'Capim Grosso',
 'Capinzal',
 'Capinzal do Norte',
 'Capinópolis',
 'Capistrano',
 'Capitão',
 'Capitão Andrade',
 'Capitão Enéas',
 'Capitão Gervásio Oliveira',
 'Capitão Leônidas Marques',
 'Capitão Poço',
 'Capitão de Campos',
 'Capitólio',
 'Capivari',
 'Capivari de Baixo',
 'Capivari do Sul',
 'Capixaba',
 'Capoeiras',
 'Caputira',
 'Capão Alto',
 'Capão Bonito',
 'Capão Bonito do Sul',
 'Capão da Canoa',
 'Capão do Cipó',
 'Capão do Leão',
 'Caracaraí',
 'Caracol',
 'Caraguatatuba',
 'Carambeí',
 'Caranaíba',
 'Carandaí',
 'Carangola',
 'Carapebus',
 'Carapicuíba',
 'Caratinga',
 'Carauari',
 'Caravelas',
 'Carazinho',
 'Caraá',
 'Caraí',
 'Caraíbas',
 'Caraúbas',
 'Caraúbas do Piauí',
 'Carbonita',
 ...]

In [9]:
dataset = (
    ambulatorio.loc[ambulatorio["no_municipio"].isin(chaves_comuns), ["co_ibge", "no_municipio", "nu_ocorrencias", "mp_municipio"]]
    .rename(columns={"nu_ocorrencias": "nu_ocorrencias_ambulatorio"})
    .merge(
        internacoes.loc[internacoes["no_municipio"].isin(chaves_comuns), ["co_ibge", "no_municipio", "nu_ocorrencias"]]
        .rename(columns={"nu_ocorrencias": "nu_ocorrencias_internacoes"}),
        on=["co_ibge", "no_municipio"],
        how="left"
    )
)

dataset["nu_ocorrencias_internacoes"] = dataset["nu_ocorrencias_internacoes"].fillna(0).astype(int)
dataset = dataset.sort_values("no_municipio").reset_index(drop=True)

dataset

,co_ibge,no_municipio,nu_ocorrencias_ambulatorio,mp_municipio,nu_ocorrencias_internacoes
0,520005,Abadia de Goiás,0,MULTIPOLYGON (((-49.384133 -16.831875999999998...,0
1,310010,Abadia dos Dourados,2,"MULTIPOLYGON (((-47.453416 -18.467321, -47.481...",0
2,520010,Abadiânia,0,"MULTIPOLYGON (((-48.77001 -16.289443, -48.7713...",0
3,150010,Abaetetuba,0,"MULTIPOLYGON (((-49.154547 -1.70176, -49.13129...",0
4,310020,Abaeté,0,"MULTIPOLYGON (((-45.650225 -19.200702, -45.650...",0
...,...,...,...,...,...
5567,430155,Áurea,0,MULTIPOLYGON (((-52.041202999999996 -27.645515...,0
5568,410115,Ângulo,0,MULTIPOLYGON (((-51.962539 -23.161618999999998...,0
5569,290050,Érico Cardoso,0,"MULTIPOLYGON (((-42.192543 -13.26948, -42.1977...",0
5570,150510,Óbidos,0,"MULTIPOLYGON (((-55.720223 2.401141, -55.70698...",0
5571,353380,Óleo,0,"MULTIPOLYGON (((-49.369586 -22.883433, -49.337...",0

In [10]:
mapa_uf = {
    "11":"RO","12":"AC","13":"AM","14":"RR","15":"PA","16":"AP","17":"TO",
    "21":"MA","22":"PI","23":"CE","24":"RN","25":"PB","26":"PE","27":"AL","28":"SE","29":"BA",
    "31":"MG","32":"ES","33":"RJ","35":"SP",
    "41":"PR","42":"SC","43":"RS",
    "50":"MS","51":"MT","52":"GO","53":"DF"
}

dataset["uf_cod"] = dataset["co_ibge"].astype(str).str.zfill(6).str[:2]
dataset["uf"] = dataset["uf_cod"].map(mapa_uf)
dataset = dataset.drop(columns=["uf_cod"])

In [11]:
dataset = dataset[dataset["nu_ocorrencias_ambulatorio"] != 0]
dataset = dataset[dataset["nu_ocorrencias_internacoes"] != 0]
dataset

,co_ibge,no_municipio,nu_ocorrencias_ambulatorio,mp_municipio,nu_ocorrencias_internacoes,uf
161,350160,Americana,3,MULTIPOLYGON (((-47.351200999999996 -22.785031...,1,SP
205,330010,Angra dos Reis,3,MULTIPOLYGON (((-44.521080999999995 -23.027292...,4,RJ
230,520110,Anápolis,3,"MULTIPOLYGON (((-48.982105 -16.405359, -49.009...",2,GO
235,520140,Aparecida de Goiânia,26,MULTIPOLYGON (((-49.363578999999994 -16.892336...,1,GO
285,270030,Arapiraca,1,"MULTIPOLYGON (((-36.690749 -9.804243999999999,...",5,AL
...,...,...,...,...,...,...
5487,293330,Vitória da Conquista,2,MULTIPOLYGON (((-40.701847 -15.076360999999999...,11,BA
5499,355700,Votorantim,41,"MULTIPOLYGON (((-47.307463 -23.561007, -47.309...",18,SP
5500,355710,Votuporanga,15,"MULTIPOLYGON (((-50.120168 -20.521651, -50.138...",1,SP
5506,510840,Várzea Grande,15,MULTIPOLYGON (((-56.145761 -15.768320999999998...,23,MT
5537,510020,Água Boa,2,"MULTIPOLYGON (((-52.33045 -14.534599, -52.3193...",3,MT

In [12]:
dataset = dataset.sort_values(by="nu_ocorrencias_internacoes", ascending=False).reset_index(drop=True)
dataset

,co_ibge,no_municipio,nu_ocorrencias_ambulatorio,mp_municipio,nu_ocorrencias_internacoes,uf
0,292740,Salvador,38,"MULTIPOLYGON (((-38.585586 -13.012673, -38.580...",115,BA
1,130260,Manaus,1,"MULTIPOLYGON (((-59.500308 -2.971896, -59.5004...",55,AM
2,410690,Curitiba,36,MULTIPOLYGON (((-49.229496 -25.349840999999998...,46,PR
3,431490,Porto Alegre,73,MULTIPOLYGON (((-51.272456999999996 -30.038631...,44,RS
4,355030,São Paulo,37,MULTIPOLYGON (((-46.611947 -23.967762999999998...,43,SP
...,...,...,...,...,...,...
166,421620,São Francisco do Sul,2,"MULTIPOLYGON (((-48.594254 -26.452177, -48.596...",1,SC
167,316860,Teófilo Otoni,6,"MULTIPOLYGON (((-41.142005 -17.949426, -41.183...",1,MG
168,317070,Varginha,4,"MULTIPOLYGON (((-45.416869 -21.667479, -45.435...",1,MG
169,317052,Urucuia,6,"MULTIPOLYGON (((-45.906118 -16.10702, -45.8929...",1,MG
170,355710,Votuporanga,15,"MULTIPOLYGON (((-50.120168 -20.521651, -50.138...",1,SP

In [13]:
dataset.to_csv("data/dataset.csv")